name: gpms
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
<<<<<<< HEAD
  flutter_modular: ^4.5.1+1
=======
  flutter_modular: ^5.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
>>>>>>> origin/feature/GPMS-39
  equatable: ^2.0.3
  get: ^4.6.1
  dartz: ^0.10.1
  path_provider: ^2.0.9
  flutter_svg: ^1.0.3
  hive: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
<<<<<<< HEAD
  flutter_lints: ^1.0.0
  modular_test: ^1.0.1+2
=======
  flutter_lints: ^2.0.1
  bloc_test: ^9.0.3
  modular_test: ^2.0.0
>>>>>>> origin/feature/GPMS-39

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/avatars/
    - assets/images/award/
    - assets/images/bishop/
    - assets/images/icon/
    - assets/images/king/
    - assets/images/knight/
    - assets/images/pawn/
    - assets/images/queen/
    - assets/images/rook/

  fonts:
    - family: Oxanium
      fonts:
        - asset: assets/fonts/Oxanium/Oxanium-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Oxanium/Oxanium-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oxanium/Oxanium-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oxanium/Oxanium-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oxanium/Oxanium-Regular.ttf
          weight: 400
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Caveat/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf
          weight: 400
